# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170128_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_complete',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
