# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20170128_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='next_repeat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
